# config info for XMem
benchmark: False
disable_long_term: False
max_mid_term_frames: 10
min_mid_term_frames: 5
max_long_term_elements: 1000
num_prototypes: 128
top_k: 30
mem_every: 5
deep_update_every: -1
save_scores: False
flip: False
size: 480
enable_long_term: True
enable_long_term_count_usage: True
