i2v_cond_time_zero: false

output_dir: "outputs/vdm"
name: "train"

pretrained_model_path: "yanqinJiang/mvdream-sd1.5-diffusers"
motion_adapter_path: "guoyww/animatediff-motion-adapter-v1-5-2"
ip_adapter_path: "h94/IP-Adapter"

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  info_path:        "./data/vdm/meta/debug.json"
  sample_size:     256
  sample_n_frames: 16

validation_data:
  prompts:
    - "A girl wearing a pair of sunglasses is dancing."
    - "A orange and brown lion is roaring."
  image_root: "examples/images"
  images:
    - "122e302ff2164d77ba345add7133725a"
    - "051a2a7ea842426f825e128fef3bf92b"
  num_inference_steps: 25
  guidance_scale: 7.5

trainable_modules:
  - "i2v."
  - "motion_modules."

unet_checkpoint_path: ""
resume_from_checkpoint: false

learning_rate:    1.e-4
train_batch_size: 1

max_train_epoch:      20
max_train_steps:      -1 # ture training iterations
checkpointing_epochs: 1
checkpointing_steps:  -1

validation_epoch:        1
validation_steps:       -1
validation_steps_tuple: [100, 200, 300]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

is_debug: false
num_workers: 32

num_views: 4

mvdream_attn_cfg:
  image_attn:
    enabled: true

motion_module_attn_cfg:
  enabled: true
  spatial_attn:
    enabled: true
    attn_cfg:
      use_spatial_encoding: true
      spatial_encoding_type: "sinusoid"
      use_camera_encoding: false
      camera_encoding_type: "sinusoid"
  image_attn:
    enabled: false
  use_alpha_blender: true

video_length: 16
